name: tensile_test
channels:
  - conda-forge
dependencies:
  - ase =3.27.0
  - damask =3.0.2
  - requests =2.32.4
  - rdflib =7.4.0
  - pyiron_snippets =1.5.0
  - flowrep =0.6.3
  - pip
  - pip:
    - coveralls
